CREATE TABLE ClickZone (
 Id INT PRIMARY KEY IDENTITY,
 X FLOAT NOT NULL,
 Y FLOAT NOT NULL
);

CREATE TABLE Zone (
 Id INT PRIMARY KEY IDENTITY,
 X1 FLOAT NOT NULL,
 Y1 FLOAT NOT NULL,
 X2 FLOAT NOT NULL,
 Y3 FLOAT NOT NULL,
);